name: השוואת מחירים של רשמי שמות מתחם ישראלים
markdown: redcarpet
pygments: true

direction: rtl
lang: he

root: //tomer.github.io/IsraeliDomains

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
